---
- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
   - mariadb
   - mariadb-server
   - mariadb-libs
   - MySQL-python

- name: Start MariaDB service
  service: name=mariadb state=started enabled=yes

- name: Create MySQL configuration file
  template: 
    src: my.cnf.j2 
    dest: /etc/my.cnf
    owner: mysql
    group: mysql
    mode: '0600'
  
- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775
  notify: restart mariadb
